language: ruby
sudo: required
dist: xenial
services:
  - docker
rvm:
  - 2.6.5
  - 2.7.0
  - ruby-head

before_install: gem install bundler
bundler_args: "--jobs=4"
cache: bundler
script:
  - bundle exec rake
